import * as React from 'react';

/** One file in the set. The caller's queue owns `state` and `progress`. */
export interface FileEntry {
  /** Stable across renders. Generated by the composite for files it accepts. */
  id: string;
  name: string;
  size?: number;
  /** The File itself, for callers that upload on save rather than on arrival. */
  file?: File;
  state?: 'queued' | 'uploading' | 'complete' | 'failed';
  /** 0–100. Required while `state === 'uploading'`. */
  progress?: number;
  error?: React.ReactNode;
  meta?: React.ReactNode;
  /** Retry this entry. Without it, Retry just resets the row to `uploading`. */
  onRetry?: (entry: FileEntry) => void;
}

export type SetStatus = 'idle' | 'busy' | 'failed' | 'invalid';

/**
 * One attachment set on one record — the aggregate the parts cannot see.
 *
 * `FileDropzone` knows only the last drop and `FileItem` only its own row, so
 * neither can answer "is this set finished?". This composite derives that from
 * the set and reports it through `onStatusChange`, which is what makes a
 * surface's Save or Release button correct.
 *
 * Controlled only: the queue belongs to whoever owns the transport, and the
 * composite stores nothing. See `specs/composite/FileUpload.spec.html`.
 */
export interface FileUploadProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'style' | 'onChange'> {
  value?: FileEntry[];
  /** Fired on select, remove and cancel. The single write path for the set. */
  onChange?: (next: FileEntry[]) => void;
  /** Names the SET. One name over several controls. */
  label?: React.ReactNode;
  /** Names the target and both routes, with the content: "Drop the revised drawing and BOM here, or browse". */
  targetLabel?: React.ReactNode;
  /** The rules, stated before the attempt. Rendered inside the target, not under the set. */
  hint?: React.ReactNode;
  /** Overrides the derived set-level message. Per-file reasons stay on their rows. */
  error?: React.ReactNode;
  /** An empty set is invalid — the only rule the composite asserts on its own. */
  required?: boolean;
  /**
   * The required message, in the record's own words ("A drawing is required
   * before ECR-2291 can be released."). Unlike `error`, setting this does not
   * clobber the rejection and failed-upload messages.
   */
  requiredMessage?: React.ReactNode;
  /**
   * Reveal the required message before the set has been touched — pass `true`
   * when a submit was attempted. The status is `'invalid'` from mount either
   * way; this controls only whether the message is shown yet.
   */
  showRequired?: boolean;
  accept?: string;
  maxSize?: number;
  /** Counted against `value.length` by the composite. `maxFiles={1}` makes the picker single-select. */
  maxFiles?: number;
  /** One size down the whole column. Rows stay on `sm` controls at both. */
  size?: 'sm' | 'md';
  /** Aggregate: the target and every row's actions go inert together. */
  disabled?: boolean;
  /** How the surface learns whether it may submit. */
  onStatusChange?: (status: SetStatus) => void;
  style?: React.CSSProperties;
}
export declare function FileUpload(props: FileUploadProps): JSX.Element;

/**
 * The same derivation the composite uses, for a surface that needs the status
 * without rendering the set. Order is `invalid → failed → busy → idle`.
 */
export declare function deriveStatus(
  value: FileEntry[],
  opts?: { required?: boolean; rejected?: number }
): SetStatus;
